// Automatically generated by astro-icon
// 8c52b7f5a9693cb9ed778499afff2e8a6adf21d2d1bf8011129489025195cf39

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "bluesky"
		| "github-logo"
		| "googlescholar"
		| "linkedin-logo"
		| "twitter";
}