// Automatically generated by astro-icon
// 500145fc4691d43f67c25316f42c675897884afb3f83097091ed1b12cf23c508

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "bluesky"
		| "github-logo"
		| "linkedin-logo";
}