// Automatically generated by astro-icon
// d39fcc1f39c0c9ef93eb320acd2fa03ea4acf245b09661a05a908833d5de05b7

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "bluesky"
		| "github-logo"
		| "linkedin-logo"
		| "twitter";
}