baseURL = 'https://keygoksmg.github.io/'
languageCode = 'en-us'
title = 'Keigo Kusumegi'
theme = 'digitalgarden'
canonifyurls = true
googleAnalytics = "G-5BLWZ3MF9C"
enableEmoji = true

[params]
  profile_img = 'Heal01.jpg'
  # profile_img = 'Heal01.jpg'

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Resume/CV'
  url = '/cv'
  weight = 2
[[menu.main]]
  name = 'Project'
  url = '/projects'
  weight = 3
[[menu.main]]
  name = 'Wiki'
  url = '/wiki'
  weight = 4
[[menu.main]]
  name = 'Blog(Japanese)'
  url = 'https://medium.com/@kusukun7'
  weight = 5



[[menu.social]]
  name = 'Twitter'
  url = 'https://twitter.com/keigoksmg'
  weight = 1
[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/Keygoksmg'
  weight = 2
[[menu.social]]
  name = 'LinkedIn'
  url = 'https://www.linkedin.com/in/keigo-kusumegi-b6127a205/?locale=en_US'
  weight = 3
[[menu.social]]
  name = 'Email'
  url = 'mailto:kusukun7@gmail.com'
  weight = 4

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true