baseURL = 'https://keygoksmg.github.io/'
languageCode = 'en-us'
title = 'Keigo Kusumegi'
theme = 'digitalgarden'
canonifyurls = true

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
# [[menu.main]]
#   name = 'Articles'
#   url = '/articles'
#   weight = 2


[[menu.social]]
  name = 'Twitter'
  url = 'https://twitter.com/Keygoksmg'
  weight = 1
[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/Keygoksmg'
  weight = 2
[[menu.social]]
  name = 'Email'
  url = 'kusukun7@gmail.com'
  weight = 3